== Intermediate Java


=== Effective Java, Second Edition

_Prentice Hall_
_By Joshua Bloch_
_ISBN: 9780321356680_
_May 2008_
_$54.99 US_
_384 pages_

Are you looking for a deeper understanding of the Java™ programming language so that you can write code that is clearer, more correct, more robust, and more reusable? Look no further! This book brings together seventy-eight indispensable programmer’s rules of thumb: working, best-practice solutions for the programming challenges you encounter every day. This highly anticipated new edition of the classic, Jolt Award-winning work has been thoroughly updated to cover Java SE 5 and Java SE 6 features introduced since the first edition. Bloch explores new design patterns and language idioms, showing you how to make the most of features ranging from generics to enums, annotations to autoboxing.

_http://my.safaribooksonline.com/book/programming/java/9780321356680?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Data Structures and Algorithms Using Java

_Jones & Bartlett Learning_
_By William McAllister_
_ISBN: 9780763757564_
_December 2008_
_$82.95 US_
_580 pages_

This book covers the entire recommended syllabus put forth by the Association of Computing Machinery (ACM) standard curriculum guidelines for "Algorithms and Data Structures." The authors main motivation for writing the text was to produce a text that was more readable and instructional than those currently in print without compromising the scope of the CS103 course material. McAllister does just that with his unique student-friendly pedagogical approach and organizational structure. The pedagogical features of the text, based on the author's 30 years of teaching experience, include succinct code examples, a unique common template used as the organizational basis of each chapter, the use of pseudocode to present the major algorithms developed in the text, 300 carefully designed figures, and a review of Java.

_http://my.safaribooksonline.com/book/programming/java/9780763757564?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Ant in Action: Java Development with Ant, Second Edition

_Manning Publications_
_By Steve Loughran & Erik Hatcher_
_ISBN: 9781932394801_
_July 2007_
_$49.99 US_
_600 pages_

This book introduces Ant and how to use it for test-driven Java application development. A single application of increasing complexity, followed throughout the book, shows how an application evolves and how to handle the problems of building and testing. Reviewers have praised the book's coverage of large-projects, Ant's advanced features, and the details and depth of the discussion are unavailable elsewhere.

_http://my.safaribooksonline.com/book/programming/java/9781932394801?cid=1107-bibilio-java-link[Read it on Safari Books Online]_

=== Maven: The Definitive Guide, First Edition

_O'Reilly Media_
B_y Sonatype Company_
_ISBN: 9780596517335_
_September 2008_
_$34.99 US_
_480 pages_

For too long, developers have worked on disorganized application projects, where every part seemed to have its own build system, and no common repository existed for information about the state of the project. Now there's help. The long-awaited official documentation to Maven is here. Written by Maven creator Jason Van Zyl and his team at Sonatype, this book clearly explains how this tool can bring order to your software development projects. Maven is largely replacing Ant as the build tool of choice for large open source Java projects because, unlike Ant, Maven is also a project management tool that can run reports, generate a project website, and facilitate communication among members of a working team. This book will help you manage development projects for software, web applications, and enterprise applications. And it comes straight from the source.

_http://my.safaribooksonline.com/book/programming/java/9780596517335?cid=1107-bibilio-java-link[Read it on Safari Books Online]_

=== Building and Testing with Gradle

_O'Reilly Media_
_By Tim Berglund, Matthew McCullough & Ken Sipe_
_ISBN: 9781449304638_
_July 2011_
_$24.99 US_
_110 pages_

Build and test software written in Java and many other languages with Gradle, the open source project automation tool that’s getting a lot of attention. This concise introduction provides numerous code examples to help you explore Gradle, both as a build tool and as a complete solution for automating the compilation, test, and release process of simple and enterprise-level applications. Discover how Gradle improves on the best ideas of Ant, Maven, and other build tools, with standards for developers who want them and lots of flexibility for those who prefer less structure.

=== Algorithms in Java, Third Edition, Parts 1-4: Fundamentals, Data Structures, Sorting, Searching

_Addison-Wesley Professional_
_By Robert Sedgewick_
_ISBN: 9780201361209_
_July 2002_
_$69.99 US_
_768 pages_

This edition of Robert Sedgewick's popular work provides current and comprehensive coverage of important algorithms for Java programmers. Michael Schidlowsky and Sedgewick have developed new Java implementations that both express the methods in a concise and direct manner and provide programmers with the practical means to test them on real applications. Many new algorithms are presented, and the explanations of each algorithm are much more detailed than in previous editions. A new text design and detailed, innovative figures, with accompanying commentary, greatly enhance the presentation. The third edition retains the successful blend of theory and practice that has made Sedgewick's work an invaluable resource for more than 400,000 programmers! Whether you are learning the algorithms for the first time or wish to have up-to-date reference material that incorporates new programming styles with classic and new algorithms, you will find a wealth of useful information in this book.

_http://my.safaribooksonline.com/book/programming/java/9780201361209?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Object-oriented Programming Using C++ and Java

_Pearson Education India_
_By Ramesh Vasappanavara, Gautam Vasappanavara & Anand Vasappanavara_
_Pearson Education India_
_ISBN: 9788131754559_
_May 2011_
_500 pages_

This book offers contemporary, comprehensive and in-depth coverage of all the concepts of object-oriented technologies, with an emphasis on problem-solving approaches as applied to C++ and Java Programming paradigms.

_http://my.safaribooksonline.com/book/programming/java/9788131754559?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Java and XML, Third Edition

_O'Reilly Media_
_By Brett McLaughlin & Justin Edelson_ 
_ISBN: 9780596101497_
_December 2006_
_$49.99 US_
_480 pages_

This third edition covers all major Java XML processing libraries, including full coverage of the SAX, DOM, StAX, JDOM, and dom4j APIs as well as the latest version of the Java API for XML Processing (JAXP) and Java Architecture for XML Binding (JAXB). The chapters on web technology have been entirely rewritten to focus on the today's most relevant topics: syndicating content with RSS and creating Web 2.0 applications.  If you are developing with Java and need to use XML, or think that you will be in the future; if you're involved in the new peer-to-peer movement, messaging, or web services; or if you're developing software for electronic commerce, this book will be an indispensable companion.

_http://my.safaribooksonline.com/book/programming/java/9780596101497?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Program Development in Java: Abstraction, Specification, and Object-Oriented Design

_Addison-Wesley Professional_
_By Barbara Liskov & John Guttag_
_ISBN: 9780201657685_
_June 2000_
_$69.99 US_
_464 pages_

Written by a world-renowned expert on programming methodology, and the winner of the 2008 Turing Award, this book shows how to build production-quality programs--programs that are reliable, easy to maintain, and quick to modify. Its emphasis is on modular program construction: how to get the modules right and how to organize a program as a collection of modules. The book presents a methodology effective for either an individual programmer, who may be writing a small program or a single module in a larger one; or a software engineer, who may be part of a team developing a complex program comprised of many modules. Both audiences will acquire a solid foundation for object-oriented program design and component-based software development from this methodology. The Java programming language is used for the book's examples. However, the techniques presented are language independent, and an introduction to key Java concepts is included for programmers who may not be familiar with the language.

_http://my.safaribooksonline.com/book/programming/java/9780201657685?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Java Puzzlers: Traps, Pitfalls, and Corner Cases

_Addison-Wesley Professional_
_By Joshua Bloch & Neal Gafter_
_ISBN: 9780321336781_
_June 2005_
_$44.99 US_
_312 pages_

In this book Bloch and Gafter dive deep into the subtleties of the Java programming language and its core libraries. Illustrated with visually stunning optical illusions, the book features 95 diabolical puzzles that educate and entertain. Anyone with a working knowledge of Java will understand the puzzles, but even the most seasoned veteran will find them challenging. The solutions go well beyond a simple explanation of the program's behavior--they show you how to avoid the underlying traps and pitfalls for good. A handy catalog of traps and pitfalls at the back of the book provides a concise taxonomy for future reference. Solve these puzzles and you'll never again fall prey to the counterintuitive or obscure behaviors that can fool even the most experienced programmers.

_http://my.safaribooksonline.com/book/programming/java/9780321336781?cid=1107-bibilio-java-link[Read it on Safari Online Books]_

=== Thinking Recursively with Java

_John Wiley & Sons_
_By Eric Roberts_
_ISBN: 9780471701460_
_November 2005_
_$44.54 US_
_187 pages_

To provide students with a more effective treatment of this difficult topic, John Wiley and Sons, Inc. published Thinking Recursively by Eric Roberts. Since its publication in 1986, Thinking Recursively has become a classic in a field in which books quickly become obsolete. By focusing on effective problem-solving strategies that enable students to "think recursively," this text has helped many students over the conceptual hurdle that recursion so often represents. To celebrate the 20th anniversary of its initial publication, John Wiley and Sons is publishing Thinking Recursively with Java, making the book even more relevant to today's students.

_http://my.safaribooksonline.com/book/programming/java/9780471701460?cid=1107-bibilio-java-link[Read it on Safari Books Online]_

=== Java 6 New Features: A Tutorial

_Brainy Software_
_By Budi Kurniawan_
_ISBN: 9780975212882_
_October 2006_
_320 pages_

For seasoned Java programmers who want to stay up to date on the latest Java tools, this guide discusses the new features of Java 6. This handbook to the new version includes updated information on Web services, a JavaScript engine that allows access to information in a Java program, JDBC 4.0, JAXB 2.0, XML digital signature APIs, more sophisticated Swing components, and improvements in Java 2D that includes a GIF image writer.

_http://my.safaribooksonline.com/book/programming/java/9780975212882?cid=1107-bibilio-java-link[Read it on Safari Online Books]_