== JVM Languages


=== Programming Scala

_O'Reilly Media_ 

_By Dean Wampler & Alex Payne_ 

_ISBN: 9780596155957_ 

_July 2009_ 

_$44.99 US_ 

_448 pages_ 


Learn how to be more productive with Scala, a new multi-paradigm language for the Java Virtual Machine (JVM) that integrates features of both object-oriented and functional programming. With this book, you'll discover why Scala is ideal for highly scalable, component-based applications that support concurrency and distribution. This book clearly explains the advantages of Scala as a JVM language. You'll learn how to leverage the wealth of Java class libraries to meet the practical needs of enterprise and Internet projects more easily. Packed with code examples, this book provides useful information on Scala's command-line tools, third-party tools, libraries, and available language-aware plugins for editors and IDEs.

_http://bit.ly/q2elR5[Read it on Safari Books Online]_

=== Programming in Scala: A Comprehensive Step-by-Step Guide, 2nd Edition

_By Martin Odersky, Lex Spoon & Bill Venners_ 

_Artima_ 

_ISBN: 9780981531649_ 

_January 2011_ 

_$54.95 US_ 

_852 pages_ 


Scala is an object-oriented programming language for the Java Virtual Machine. In addition to being object-oriented, Scala is also a functional language, and combines the best approaches to OO and functional programming.  In Italian, Scala means a stairway, or steps indeed, Scala lets you step up to a programming environment that incorporates some of the best recent thinking in programming language design while also letting you use all your existing Java code.  Artima is very pleased to publish a new edition of the best-selling book on Scala, written by the designer of the language, Martin Odersky. Co-authored by Lex Spoon and Bill Venners, this book takes a step-by-step tutorial approach to teaching you Scala. Starting with the fundamental elements of the language, Programming in Scala introduces functional programming from the practitioner's perspective, and describes advanced language features that can make you a better, more productive developer.

===  Clojure Programming

_O'Reilly Media_ 

_By Chas Emerick, Brian Carper & Christophe Grand_ 

_ISBN: 9781449394707_ 

_Septmeber 2011_ 

_$29.99 US_ 

_400 pages_ 


The Clojure language is a practical alternative for everyday programming that offers expressivity rivaling other dynamic languages like Ruby and Python, but allows one to seamlessly take advantage of Java libraries, services, and all of the resources of the JVM ecosystem. This book helps you learn the fundamentals of Clojure with examples relating it to the languages you know already—whether you're focused on data modeling, concurrency and parallelism, web programming, statistics and data analysis, and more.

_http://my.safaribooksonline.com/book/programming/clojure/9781449310387?cid=1107-biblio-java-link[Read it on Safari Online Books]_ 


=== JRuby Cookbook

_O'Reilly Media_ 

_By Justin Edelson & Henry Liu_ 

_ISBN: 9780596519803_ 

_November 2008_ 

_$34.99 US_ 

_224 pages_ 


If you're interested in JRuby, you probably don't need a tutorial on Ruby, Rails, or Java -- you just need to know how to get things done. This Cookbook offers practical solutions for using the Java implementation of the Ruby language, with targeted recipes for deploying Rails web applications on Java servers, integrating JRuby code with Java technologies, developing JRuby desktop applications with Java toolkits, and more. The JRuby interpreter combines Ruby's simplicity and ease of use with Java's extensive libraries and technologies, a potent blend that opens new possibilities for Ruby, Rails, and Java. This Cookbook helps you take full advantage of JRuby's potential.

_http://bit.ly/qxXi3t[Read it on Safari Books Online]_

=== Grails In Action

_Manning Publications_ 

_By Glen Smith & Peter Ledbrook_ 

_ISBN: 9781933988931_ 

_June 2009_ 

_$44.99 US_ 

_520 pages_ 


For web developers used to wrestling with Java and XML, Grails is a breath of fresh air. Developers are instantly productive, picking up all the benefits of the Ruby-based Rails framework without giving up any of the power of Java. This book is a comprehensive look at Grails for Java developers. It covers the nuts and bolts of the core Grails components and is jam-packed with tutorials, techniques, and insights from the trenches. The book also covers using Grails with existing Java technology, like Spring, Hibernate, and EJBs.

_http://bit.ly/oDirQP[Read it on Safari Books Online]_

=== Groovy in Action

_Manning Publications_ 

_by Dierk Koenig, Andrew Glover, Paul King, Guillaume Laforge & Jon Skeet_ 

_ISBN: 9781932394849_ 

_January 2007_ 

_$49.99 US_ 

_696 pages_ 


Groovy brings to Java many of the features that have made Ruby popular. Groovy in Action is a comprehensive guide to Groovy programming, introducing Java developers to the dynamic features that Groovy provides. To bring you Groovy in Action, Manning again went to the source by working with a team of expert authors including both members and the manager of the Groovy Project team. The result is the true definitive guide to the new Groovy language. Groovy in Action introduces Groovy by example, presenting lots of reusable code while explaining the underlying concepts. Java developers new to Groovy find a smooth transition into the dynamic programming world. Groovy experts gain a solid reference that challenges them to explore Groovy deeply and creatively.

_http://techbus.safaribooksonline.com/book/programming/java/9781932394849[Read it on Safari Online Books]_ 


****
Safari Books Online provides full access to all of the resources in this bibliography. For a free trial, go to http://safaribooksonline.com/oscon11
****
